/**
 * exportPPT.ts — pptxgenjs를 이용한 PPT 슬라이드 생성
 * 차트 이미지(base64) + KPI 요약 + 인사이트 코멘트를 1장 슬라이드로 내보냅니다.
 */

export interface PPTOptions {
  chartTitle:  string;
  chartImage:  string;  // base64 PNG (html2canvas 결과)
  kpiText?:    string;  // 예: "LGEIN: +76% | LGEPH: +110%"
  insightLines?: string[];  // 최대 3줄
  layout?: '16x9' | '4x3';
}

export async function exportToPPT(opts: PPTOptions): Promise<void> {
  // pptxgenjs는 클라이언트 전용이므로 dynamic import
  const PptxGenJS = (await import('pptxgenjs')).default;
  const pptx = new PptxGenJS();

  // 레이아웃
  if (opts.layout === '4x3') {
    pptx.layout = 'LAYOUT_4x3';
  } else {
    pptx.layout = 'LAYOUT_WIDE'; // 16x9
  }

  const slide = pptx.addSlide();

  // ── 배경 ─────────────────────────────────────────────
  slide.background = { color: '0F1628' };

  // ── 제목 ─────────────────────────────────────────────
  slide.addText(opts.chartTitle || 'EasyGraph 분석 리포트', {
    x: 0.4, y: 0.15, w: 9.2, h: 0.55,
    fontSize: 22, bold: true, color: 'F0F4FF',
    fontFace: 'Malgun Gothic',
  });

  // ── 구분선 ────────────────────────────────────────────
  slide.addShape('line' as Parameters<typeof slide.addShape>[0], {
    x: 0.4, y: 0.75, w: 9.2, h: 0,
    line: { color: '00D4FF', width: 1 },
  });

  // ── 차트 이미지 ──────────────────────────────────────
  if (opts.chartImage) {
    slide.addImage({
      data: opts.chartImage,
      x: 0.4, y: 0.9, w: 9.2, h: 4.8,
    });
  }

  // ── KPI 요약 텍스트 ───────────────────────────────────
  if (opts.kpiText) {
    slide.addText(opts.kpiText, {
      x: 0.4, y: 5.85, w: 9.2, h: 0.4,
      fontSize: 11, color: '8892B0',
      fontFace: 'Malgun Gothic',
      align: 'center',
    });
  }

  // ── 인사이트 코멘트 ───────────────────────────────────
  if (opts.insightLines?.length) {
    const text = opts.insightLines.map((line, i) => ({
      text: `${['①','②','③'][i] ?? '•'} ${line}`,
      options: { breakLine: true },
    }));
    slide.addText(text, {
      x: 0.4, y: 6.3, w: 9.2, h: 1.0,
      fontSize: 10, color: 'A8B2C8',
      fontFace: 'Malgun Gothic',
    });
  }

  // ── 워터마크 ──────────────────────────────────────────
  slide.addText('Generated by EasyGraph', {
    x: 7.5, y: 7.3, w: 2.0, h: 0.25,
    fontSize: 8, color: '374151',
    fontFace: 'Malgun Gothic',
    align: 'right',
  });

  // ── 저장 ──────────────────────────────────────────────
  const fileName = `EasyGraph_${opts.chartTitle.replace(/\s/g,'_') || 'Report'}_${
    new Date().toISOString().slice(0,10)
  }.pptx`;
  await pptx.writeFile({ fileName });
}
